### ISSUE TITLE
M - Customer can add a product to sell

### ISSUE THREAD

**Issue by Megraohoh** [Hypnotic-Herons/sprint-3#20]
QUESTIONS: What is type vs. category = these are the same thing Ex: electronics

- [ ] *New*  Models > user > user.py
     - [ ] Class name(s): User 
- [ ] File name: Models > product > product.py
     - [ ] Add field names: type, category, 
     date_added, rating, like
- [ ] *New* Forms > product > product_add.py
- [ ] *New* Templates > product > product_add.py
- [ ] *New*  Views > product_add.py
     - [ ] method in Views > product_add.py = def product_add(req)

- [ ] Doc strings required: Author, Purpose, File Edited by

Given the user is not authenticated
When any view renders
Then the Sell a Product affordance will not be visible

- [ ] Authentication required for view

Given the user is authenticated
When the user clicks on the Sell a product button in the menu bar
Then the user will be presented with a product form

- [ ] Menu option available for "Sell a Product"
- [ ] Product form has been created; appears on click.

Given the user has filled in all fields of the product form with valid information
When the user clicks the Sell button
Then the user will be redirected to the product detail view for that product

- [ ] Form validation passed & On click--product detail view

Given the user has filled in all fields of the product form with any invalid information
When the user clicks the Sell button
Then the user will be immediately notified with error information for each invalid value

- [ ] Form validation failed & notification by input fields 

Final Steps: 
- [ ] Update Readme
- [ ] Create PR for team review
- [ ] Move ticket to appropriate next column.

**Comment by Deanna2000** [comment]
User will click a link in the navbar on the logged in home view: 

![logged in](https://user-images.githubusercontent.com/4274592/44286641-66ffc180-a22f-11e8-9db4-47f2f397e807.png)

**Comment by Deanna2000** [comment]
This is the form you'll see when you click on the "sell a product" link the navbar: 

![sell a product](https://user-images.githubusercontent.com/4274592/44287551-d88d3f00-a232-11e8-97d1-f995df5272d2.png)
